# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configFileWizard.ui'
#
# Created: Mon Feb 17 11:52:27 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(477, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Resources/havok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Wizard.setWindowIcon(icon)
        Wizard.setWizardStyle(QtGui.QWizard.ClassicStyle)
        Wizard.setOptions(QtGui.QWizard.NoBackButtonOnStartPage)
        self.wizardPage0 = QtGui.QWizardPage()
        self.wizardPage0.setObjectName("wizardPage0")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.wizardPage0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtGui.QSpacerItem(20, 57, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_Typical = QtGui.QRadioButton(self.wizardPage0)
        self.radioButton_Typical.setChecked(True)
        self.radioButton_Typical.setObjectName("radioButton_Typical")
        self.verticalLayout_6.addWidget(self.radioButton_Typical)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.radioButton_Customized = QtGui.QRadioButton(self.wizardPage0)
        self.radioButton_Customized.setObjectName("radioButton_Customized")
        self.verticalLayout_6.addWidget(self.radioButton_Customized)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        spacerItem2 = QtGui.QSpacerItem(20, 56, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        Wizard.addPage(self.wizardPage0)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.verticalLayout = QtGui.QVBoxLayout(self.wizardPage1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.wizardPage1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_TerrainCmpType = QtGui.QComboBox(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_TerrainCmpType.sizePolicy().hasHeightForWidth())
        self.comboBox_TerrainCmpType.setSizePolicy(sizePolicy)
        self.comboBox_TerrainCmpType.setObjectName("comboBox_TerrainCmpType")
        self.comboBox_TerrainCmpType.addItem("")
        self.comboBox_TerrainCmpType.addItem("")
        self.comboBox_TerrainCmpType.addItem("")
        self.comboBox_TerrainCmpType.addItem("")
        self.comboBox_TerrainCmpType.addItem("")
        self.gridLayout.addWidget(self.comboBox_TerrainCmpType, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.wizardPage1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_TerrainExp = QtGui.QLineEdit(self.wizardPage1)
        self.lineEdit_TerrainExp.setObjectName("lineEdit_TerrainExp")
        self.gridLayout.addWidget(self.lineEdit_TerrainExp, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.wizardPage1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_TerrainPageIn = QtGui.QSpinBox(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_TerrainPageIn.sizePolicy().hasHeightForWidth())
        self.spinBox_TerrainPageIn.setSizePolicy(sizePolicy)
        self.spinBox_TerrainPageIn.setMinimum(1)
        self.spinBox_TerrainPageIn.setMaximum(99999999)
        self.spinBox_TerrainPageIn.setProperty("value", 2000)
        self.spinBox_TerrainPageIn.setObjectName("spinBox_TerrainPageIn")
        self.gridLayout.addWidget(self.spinBox_TerrainPageIn, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.wizardPage1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinBox__TerrainPageOut = QtGui.QSpinBox(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox__TerrainPageOut.sizePolicy().hasHeightForWidth())
        self.spinBox__TerrainPageOut.setSizePolicy(sizePolicy)
        self.spinBox__TerrainPageOut.setMinimum(1)
        self.spinBox__TerrainPageOut.setMaximum(99999999)
        self.spinBox__TerrainPageOut.setProperty("value", 4000)
        self.spinBox__TerrainPageOut.setObjectName("spinBox__TerrainPageOut")
        self.gridLayout.addWidget(self.spinBox__TerrainPageOut, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.wizardPage1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.spinBox__TerrainForceLoad = QtGui.QSpinBox(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox__TerrainForceLoad.sizePolicy().hasHeightForWidth())
        self.spinBox__TerrainForceLoad.setSizePolicy(sizePolicy)
        self.spinBox__TerrainForceLoad.setMinimum(1)
        self.spinBox__TerrainForceLoad.setMaximum(99999999)
        self.spinBox__TerrainForceLoad.setProperty("value", 1000)
        self.spinBox__TerrainForceLoad.setObjectName("spinBox__TerrainForceLoad")
        self.gridLayout.addWidget(self.spinBox__TerrainForceLoad, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wizardPage2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtGui.QLabel(self.wizardPage2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.wizardPage2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEdit_MeshExp = QtGui.QLineEdit(self.wizardPage2)
        self.lineEdit_MeshExp.setObjectName("lineEdit_MeshExp")
        self.gridLayout_3.addWidget(self.lineEdit_MeshExp, 1, 1, 1, 1)
        self.comboBox_MeshCmpType = QtGui.QComboBox(self.wizardPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_MeshCmpType.sizePolicy().hasHeightForWidth())
        self.comboBox_MeshCmpType.setSizePolicy(sizePolicy)
        self.comboBox_MeshCmpType.setObjectName("comboBox_MeshCmpType")
        self.comboBox_MeshCmpType.addItem("")
        self.comboBox_MeshCmpType.addItem("")
        self.comboBox_MeshCmpType.addItem("")
        self.comboBox_MeshCmpType.addItem("")
        self.comboBox_MeshCmpType.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_MeshCmpType, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        Wizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName("wizardPage3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.wizardPage3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.spinBox_PhysicsPageIn = QtGui.QSpinBox(self.wizardPage3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_PhysicsPageIn.sizePolicy().hasHeightForWidth())
        self.spinBox_PhysicsPageIn.setSizePolicy(sizePolicy)
        self.spinBox_PhysicsPageIn.setMinimum(1)
        self.spinBox_PhysicsPageIn.setMaximum(99999999)
        self.spinBox_PhysicsPageIn.setProperty("value", 100000)
        self.spinBox_PhysicsPageIn.setObjectName("spinBox_PhysicsPageIn")
        self.gridLayout_4.addWidget(self.spinBox_PhysicsPageIn, 0, 1, 1, 1)
        self.spinBox_PhysicsPageOut = QtGui.QSpinBox(self.wizardPage3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_PhysicsPageOut.sizePolicy().hasHeightForWidth())
        self.spinBox_PhysicsPageOut.setSizePolicy(sizePolicy)
        self.spinBox_PhysicsPageOut.setMinimum(1)
        self.spinBox_PhysicsPageOut.setMaximum(99999999)
        self.spinBox_PhysicsPageOut.setProperty("value", 200000)
        self.spinBox_PhysicsPageOut.setObjectName("spinBox_PhysicsPageOut")
        self.gridLayout_4.addWidget(self.spinBox_PhysicsPageOut, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.wizardPage3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.wizardPage3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.wizardPage3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.spinBox_PhysicsForceLoad = QtGui.QSpinBox(self.wizardPage3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_PhysicsForceLoad.sizePolicy().hasHeightForWidth())
        self.spinBox_PhysicsForceLoad.setSizePolicy(sizePolicy)
        self.spinBox_PhysicsForceLoad.setMinimum(1)
        self.spinBox_PhysicsForceLoad.setMaximum(99999999)
        self.spinBox_PhysicsForceLoad.setProperty("value", 1)
        self.spinBox_PhysicsForceLoad.setObjectName("spinBox_PhysicsForceLoad")
        self.gridLayout_4.addWidget(self.spinBox_PhysicsForceLoad, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        Wizard.addPage(self.wizardPage3)
        self.wizardPage4 = QtGui.QWizardPage()
        self.wizardPage4.setObjectName("wizardPage4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.wizardPage4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem9 = QtGui.QSpacerItem(20, 64, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtGui.QLabel(self.wizardPage4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.comboBox_TreeCmpType = QtGui.QComboBox(self.wizardPage4)
        self.comboBox_TreeCmpType.setObjectName("comboBox_TreeCmpType")
        self.comboBox_TreeCmpType.addItem("")
        self.comboBox_TreeCmpType.addItem("")
        self.comboBox_TreeCmpType.addItem("")
        self.comboBox_TreeCmpType.addItem("")
        self.comboBox_TreeCmpType.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_TreeCmpType, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.wizardPage4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 1)
        self.lineEdit_TreeExp = QtGui.QLineEdit(self.wizardPage4)
        self.lineEdit_TreeExp.setObjectName("lineEdit_TreeExp")
        self.gridLayout_5.addWidget(self.lineEdit_TreeExp, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.wizardPage4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.lineEdit_TreeReplacement = QtGui.QLineEdit(self.wizardPage4)
        self.lineEdit_TreeReplacement.setText("")
        self.lineEdit_TreeReplacement.setObjectName("lineEdit_TreeReplacement")
        self.gridLayout_5.addWidget(self.lineEdit_TreeReplacement, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_5)
        spacerItem10 = QtGui.QSpacerItem(20, 63, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        Wizard.addPage(self.wizardPage4)
        self.wizardPage5 = QtGui.QWizardPage()
        self.wizardPage5.setObjectName("wizardPage5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.wizardPage5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem11 = QtGui.QSpacerItem(20, 89, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_14 = QtGui.QLabel(self.wizardPage5)
        self.label_14.setMinimumSize(QtCore.QSize(85, 0))
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_ConfigFilePath = QtGui.QComboBox(self.wizardPage5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_ConfigFilePath.sizePolicy().hasHeightForWidth())
        self.comboBox_ConfigFilePath.setSizePolicy(sizePolicy)
        self.comboBox_ConfigFilePath.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox_ConfigFilePath.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_ConfigFilePath.setEditable(True)
        self.comboBox_ConfigFilePath.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.comboBox_ConfigFilePath.setObjectName("comboBox_ConfigFilePath")
        self.horizontalLayout.addWidget(self.comboBox_ConfigFilePath)
        self.pushButton_ConfigFile = QtGui.QPushButton(self.wizardPage5)
        self.pushButton_ConfigFile.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_ConfigFile.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_ConfigFile.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Resources/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ConfigFile.setIcon(icon1)
        self.pushButton_ConfigFile.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_ConfigFile.setObjectName("pushButton_ConfigFile")
        self.horizontalLayout.addWidget(self.pushButton_ConfigFile)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 2)
        self.label_15 = QtGui.QLabel(self.wizardPage5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(0, 0))
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 2)
        self.lineEdit_ConfigFile = QtGui.QLineEdit(self.wizardPage5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ConfigFile.sizePolicy().hasHeightForWidth())
        self.lineEdit_ConfigFile.setSizePolicy(sizePolicy)
        self.lineEdit_ConfigFile.setObjectName("lineEdit_ConfigFile")
        self.gridLayout_2.addWidget(self.lineEdit_ConfigFile, 1, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        spacerItem12 = QtGui.QSpacerItem(20, 88, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        Wizard.addPage(self.wizardPage5)
        self.wizardPage6 = QtGui.QWizardPage()
        self.wizardPage6.setObjectName("wizardPage6")
        self.gridLayout_6 = QtGui.QGridLayout(self.wizardPage6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textBrowser = QtGui.QTextBrowser(self.wizardPage6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_6.addWidget(self.textBrowser, 0, 0, 1, 1)
        Wizard.addPage(self.wizardPage6)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(QtGui.QApplication.translate("Wizard", "Config File Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage0.setTitle(QtGui.QApplication.translate("Wizard", "<h3>Introduction", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage0.setSubTitle(QtGui.QApplication.translate("Wizard", "Please select a setup way.", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Typical.setToolTip(QtGui.QApplication.translate("Wizard", "This is the most comman way.", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Typical.setText(QtGui.QApplication.translate("Wizard", "Typical", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Customized.setToolTip(QtGui.QApplication.translate("Wizard", "This allows you to customize the settings.", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Customized.setText(QtGui.QApplication.translate("Wizard", "Customized", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage1.setTitle(QtGui.QApplication.translate("Wizard", "<h3>Step 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage1.setSubTitle(QtGui.QApplication.translate("Wizard", "Setup terrain tiles.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Wizard", "Comparison Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_TerrainCmpType.setItemText(0, QtGui.QApplication.translate("Wizard", "REGEX", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_TerrainCmpType.setItemText(1, QtGui.QApplication.translate("Wizard", "EQUAL_COMPARE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_TerrainCmpType.setItemText(2, QtGui.QApplication.translate("Wizard", "NOT_EQUAL_COMPARE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_TerrainCmpType.setItemText(3, QtGui.QApplication.translate("Wizard", "WILDCARD_EQUAL_COMPARE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_TerrainCmpType.setItemText(4, QtGui.QApplication.translate("Wizard", "WILDCARD_NOT_EQUAL_COMPARE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Wizard", "Expression:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_TerrainExp.setText(QtGui.QApplication.translate("Wizard", ".*flight.*", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Wizard", "Page In Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Wizard", "Page Out Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Wizard", "Force Loaded Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage2.setTitle(QtGui.QApplication.translate("Wizard", "<h3>Step 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage2.setSubTitle(QtGui.QApplication.translate("Wizard", "Setup meshes.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Wizard", "Comparison Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Wizard", "Expression:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_MeshExp.setText(QtGui.QApplication.translate("Wizard", "(?!(.*flight.*)).*", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_MeshCmpType.setItemText(0, QtGui.QApplication.translate("Wizard", "REGEX", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_MeshCmpType.setItemText(1, QtGui.QApplication.translate("Wizard", "EQUAL_COMPARE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_MeshCmpType.setItemText(2, QtGui.QApplication.translate("Wizard", "NOT_EQUAL_COMPARE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_MeshCmpType.setItemText(3, QtGui.QApplication.translate("Wizard", "WILDCARD_EQUAL_COMPARE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_MeshCmpType.setItemText(4, QtGui.QApplication.translate("Wizard", "WILDCARD_NOT_EQUAL_COMPARE", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage3.setTitle(QtGui.QApplication.translate("Wizard", "<h3>Step 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage3.setSubTitle(QtGui.QApplication.translate("Wizard", "Setup the physics zone.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Wizard", "Page Out Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Wizard", "Page In Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Wizard", "Force Loaded Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage4.setTitle(QtGui.QApplication.translate("Wizard", "<h3>Step 4:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage4.setSubTitle(QtGui.QApplication.translate("Wizard", "Setup speedtrees.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Wizard", "Comparison Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_TreeCmpType.setItemText(0, QtGui.QApplication.translate("Wizard", "REGEX", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_TreeCmpType.setItemText(1, QtGui.QApplication.translate("Wizard", "EQUAL_COMPARE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_TreeCmpType.setItemText(2, QtGui.QApplication.translate("Wizard", "NOT_EQUAL_COMPARE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_TreeCmpType.setItemText(3, QtGui.QApplication.translate("Wizard", "WILDCARD_EQUAL_COMPARE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_TreeCmpType.setItemText(4, QtGui.QApplication.translate("Wizard", "WILDCARD_NOT_EQUAL_COMPARE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Wizard", "Expression:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_TreeExp.setText(QtGui.QApplication.translate("Wizard", ".*tree.*", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Wizard", "Replacement:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage5.setTitle(QtGui.QApplication.translate("Wizard", "<h3>Step 5:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage5.setSubTitle(QtGui.QApplication.translate("Wizard", "Save the settings.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setToolTip(QtGui.QApplication.translate("Wizard", "System configuration file.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Wizard", "Save settings to:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ConfigFilePath.setToolTip(QtGui.QApplication.translate("Wizard", "System configuration file.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setToolTip(QtGui.QApplication.translate("Wizard", "System configuration file.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Wizard", "File Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ConfigFile.setText(QtGui.QApplication.translate("Wizard", "Config.xml", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage6.setTitle(QtGui.QApplication.translate("Wizard", "<h3>Conclusion", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage6.setSubTitle(QtGui.QApplication.translate("Wizard", "Overview of the settings.", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
