# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainDialog.ui'
#
# Created: Mon Feb 17 16:17:19 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainDialog(object):
    def setupUi(self, mainDialog):
        mainDialog.setObjectName("mainDialog")
        mainDialog.resize(520, 792)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainDialog.sizePolicy().hasHeightForWidth())
        mainDialog.setSizePolicy(sizePolicy)
        mainDialog.setMinimumSize(QtCore.QSize(520, 0))
        mainDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Resources/havok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainDialog.setWindowIcon(icon)
        self.verticalLayout_4 = QtGui.QVBoxLayout(mainDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtGui.QLabel(mainDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        self.label.setStyleSheet("background-color: transparent; color: #ffaa00; font-size: 21pt;  qproperty-alignment: AlignCenter;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtGui.QLabel(mainDialog)
        self.label_6.setMinimumSize(QtCore.QSize(95, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.comboBox_Profile = QtGui.QComboBox(mainDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Profile.sizePolicy().hasHeightForWidth())
        self.comboBox_Profile.setSizePolicy(sizePolicy)
        self.comboBox_Profile.setEditable(False)
        self.comboBox_Profile.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.comboBox_Profile.setObjectName("comboBox_Profile")
        self.horizontalLayout_3.addWidget(self.comboBox_Profile)
        self.pushButton_renameProfile = QtGui.QPushButton(mainDialog)
        self.pushButton_renameProfile.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_renameProfile.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_renameProfile.setStyleSheet("")
        self.pushButton_renameProfile.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Resources/pencilangled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_renameProfile.setIcon(icon1)
        self.pushButton_renameProfile.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_renameProfile.setFlat(False)
        self.pushButton_renameProfile.setObjectName("pushButton_renameProfile")
        self.horizontalLayout_3.addWidget(self.pushButton_renameProfile)
        self.pushButton_AddProfile = QtGui.QPushButton(mainDialog)
        self.pushButton_AddProfile.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_AddProfile.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_AddProfile.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Resources/page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_AddProfile.setIcon(icon2)
        self.pushButton_AddProfile.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_AddProfile.setObjectName("pushButton_AddProfile")
        self.horizontalLayout_3.addWidget(self.pushButton_AddProfile)
        self.pushButton_DelProfile = QtGui.QPushButton(mainDialog)
        self.pushButton_DelProfile.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_DelProfile.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_DelProfile.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Resources/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_DelProfile.setIcon(icon3)
        self.pushButton_DelProfile.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_DelProfile.setObjectName("pushButton_DelProfile")
        self.horizontalLayout_3.addWidget(self.pushButton_DelProfile)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.groupBox_InputSettings = QtGui.QGroupBox(mainDialog)
        self.groupBox_InputSettings.setAcceptDrops(False)
        self.groupBox_InputSettings.setToolTip("")
        self.groupBox_InputSettings.setFlat(False)
        self.groupBox_InputSettings.setCheckable(False)
        self.groupBox_InputSettings.setObjectName("groupBox_InputSettings")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_InputSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.groupBox_InputSettings)
        self.label_2.setMinimumSize(QtCore.QSize(85, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_Converter = QtGui.QComboBox(self.groupBox_InputSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Converter.sizePolicy().hasHeightForWidth())
        self.comboBox_Converter.setSizePolicy(sizePolicy)
        self.comboBox_Converter.setEditable(False)
        self.comboBox_Converter.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.comboBox_Converter.setObjectName("comboBox_Converter")
        self.horizontalLayout.addWidget(self.comboBox_Converter)
        self.pushButton_Converter = QtGui.QPushButton(self.groupBox_InputSettings)
        self.pushButton_Converter.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_Converter.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_Converter.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Resources/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Converter.setIcon(icon4)
        self.pushButton_Converter.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_Converter.setObjectName("pushButton_Converter")
        self.horizontalLayout.addWidget(self.pushButton_Converter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtGui.QLabel(self.groupBox_InputSettings)
        self.label_4.setMinimumSize(QtCore.QSize(85, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.comboBox_InputFile = QtGui.QComboBox(self.groupBox_InputSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_InputFile.sizePolicy().hasHeightForWidth())
        self.comboBox_InputFile.setSizePolicy(sizePolicy)
        self.comboBox_InputFile.setAcceptDrops(False)
        self.comboBox_InputFile.setEditable(False)
        self.comboBox_InputFile.setMaxVisibleItems(25)
        self.comboBox_InputFile.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.comboBox_InputFile.setObjectName("comboBox_InputFile")
        self.horizontalLayout_5.addWidget(self.comboBox_InputFile)
        self.pushButton_InputFile = QtGui.QPushButton(self.groupBox_InputSettings)
        self.pushButton_InputFile.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_InputFile.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_InputFile.setText("")
        self.pushButton_InputFile.setIcon(icon4)
        self.pushButton_InputFile.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_InputFile.setObjectName("pushButton_InputFile")
        self.horizontalLayout_5.addWidget(self.pushButton_InputFile)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_InputSettings)
        self.label_3.setMinimumSize(QtCore.QSize(85, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox_OpenFlightPath = QtGui.QComboBox(self.groupBox_InputSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_OpenFlightPath.sizePolicy().hasHeightForWidth())
        self.comboBox_OpenFlightPath.setSizePolicy(sizePolicy)
        self.comboBox_OpenFlightPath.setEditable(False)
        self.comboBox_OpenFlightPath.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.comboBox_OpenFlightPath.setObjectName("comboBox_OpenFlightPath")
        self.horizontalLayout_2.addWidget(self.comboBox_OpenFlightPath)
        self.pushButton__OpenFlightPath = QtGui.QPushButton(self.groupBox_InputSettings)
        self.pushButton__OpenFlightPath.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton__OpenFlightPath.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton__OpenFlightPath.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Resources/preferences.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton__OpenFlightPath.setIcon(icon5)
        self.pushButton__OpenFlightPath.setIconSize(QtCore.QSize(14, 14))
        self.pushButton__OpenFlightPath.setObjectName("pushButton__OpenFlightPath")
        self.horizontalLayout_2.addWidget(self.pushButton__OpenFlightPath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtGui.QLabel(self.groupBox_InputSettings)
        self.label_8.setMinimumSize(QtCore.QSize(85, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.comboBox_TextureInput = QtGui.QComboBox(self.groupBox_InputSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_TextureInput.sizePolicy().hasHeightForWidth())
        self.comboBox_TextureInput.setSizePolicy(sizePolicy)
        self.comboBox_TextureInput.setEditable(False)
        self.comboBox_TextureInput.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.comboBox_TextureInput.setObjectName("comboBox_TextureInput")
        self.horizontalLayout_7.addWidget(self.comboBox_TextureInput)
        self.pushButton_TextureInput = QtGui.QPushButton(self.groupBox_InputSettings)
        self.pushButton_TextureInput.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TextureInput.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_TextureInput.setText("")
        self.pushButton_TextureInput.setIcon(icon5)
        self.pushButton_TextureInput.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_TextureInput.setObjectName("pushButton_TextureInput")
        self.horizontalLayout_7.addWidget(self.pushButton_TextureInput)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtGui.QLabel(self.groupBox_InputSettings)
        self.label_7.setMinimumSize(QtCore.QSize(85, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.comboBox_ConfigFile = QtGui.QComboBox(self.groupBox_InputSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_ConfigFile.sizePolicy().hasHeightForWidth())
        self.comboBox_ConfigFile.setSizePolicy(sizePolicy)
        self.comboBox_ConfigFile.setEditable(False)
        self.comboBox_ConfigFile.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.comboBox_ConfigFile.setObjectName("comboBox_ConfigFile")
        self.horizontalLayout_6.addWidget(self.comboBox_ConfigFile)
        self.pushButton_ConfigFile = QtGui.QPushButton(self.groupBox_InputSettings)
        self.pushButton_ConfigFile.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_ConfigFile.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_ConfigFile.setText("")
        self.pushButton_ConfigFile.setIcon(icon4)
        self.pushButton_ConfigFile.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_ConfigFile.setObjectName("pushButton_ConfigFile")
        self.horizontalLayout_6.addWidget(self.pushButton_ConfigFile)
        self.pushButton_ReadConfigFile = QtGui.QPushButton(self.groupBox_InputSettings)
        self.pushButton_ReadConfigFile.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_ReadConfigFile.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_ReadConfigFile.setText("")
        self.pushButton_ReadConfigFile.setIcon(icon5)
        self.pushButton_ReadConfigFile.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_ReadConfigFile.setObjectName("pushButton_ReadConfigFile")
        self.horizontalLayout_6.addWidget(self.pushButton_ReadConfigFile)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addWidget(self.groupBox_InputSettings)
        self.groupBox_OutputSettings = QtGui.QGroupBox(mainDialog)
        self.groupBox_OutputSettings.setFlat(False)
        self.groupBox_OutputSettings.setCheckable(False)
        self.groupBox_OutputSettings.setObjectName("groupBox_OutputSettings")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_OutputSettings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_16 = QtGui.QLabel(self.groupBox_OutputSettings)
        self.label_16.setMinimumSize(QtCore.QSize(100, 0))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_15.addWidget(self.label_16)
        self.comboBox_WorkPath = QtGui.QComboBox(self.groupBox_OutputSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_WorkPath.sizePolicy().hasHeightForWidth())
        self.comboBox_WorkPath.setSizePolicy(sizePolicy)
        self.comboBox_WorkPath.setEditable(True)
        self.comboBox_WorkPath.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.comboBox_WorkPath.setObjectName("comboBox_WorkPath")
        self.horizontalLayout_15.addWidget(self.comboBox_WorkPath)
        self.pushButton_WorkPath = QtGui.QPushButton(self.groupBox_OutputSettings)
        self.pushButton_WorkPath.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_WorkPath.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_WorkPath.setText("")
        self.pushButton_WorkPath.setIcon(icon4)
        self.pushButton_WorkPath.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_WorkPath.setObjectName("pushButton_WorkPath")
        self.horizontalLayout_15.addWidget(self.pushButton_WorkPath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_19 = QtGui.QLabel(self.groupBox_OutputSettings)
        self.label_19.setMinimumSize(QtCore.QSize(100, 0))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_25.addWidget(self.label_19)
        self.lineEdit_LayerOutput = QtGui.QLineEdit(self.groupBox_OutputSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_LayerOutput.sizePolicy().hasHeightForWidth())
        self.lineEdit_LayerOutput.setSizePolicy(sizePolicy)
        self.lineEdit_LayerOutput.setProperty("editable", True)
        self.lineEdit_LayerOutput.setObjectName("lineEdit_LayerOutput")
        self.horizontalLayout_25.addWidget(self.lineEdit_LayerOutput)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_20 = QtGui.QLabel(self.groupBox_OutputSettings)
        self.label_20.setMinimumSize(QtCore.QSize(100, 0))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_26.addWidget(self.label_20)
        self.lineEdit_PhysicsOutput = QtGui.QLineEdit(self.groupBox_OutputSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_PhysicsOutput.sizePolicy().hasHeightForWidth())
        self.lineEdit_PhysicsOutput.setSizePolicy(sizePolicy)
        self.lineEdit_PhysicsOutput.setProperty("editable", True)
        self.lineEdit_PhysicsOutput.setObjectName("lineEdit_PhysicsOutput")
        self.horizontalLayout_26.addWidget(self.lineEdit_PhysicsOutput)
        self.verticalLayout_2.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_18 = QtGui.QLabel(self.groupBox_OutputSettings)
        self.label_18.setMinimumSize(QtCore.QSize(100, 0))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.lineEdit_MeshOutput = QtGui.QLineEdit(self.groupBox_OutputSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MeshOutput.sizePolicy().hasHeightForWidth())
        self.lineEdit_MeshOutput.setSizePolicy(sizePolicy)
        self.lineEdit_MeshOutput.setProperty("editable", True)
        self.lineEdit_MeshOutput.setObjectName("lineEdit_MeshOutput")
        self.horizontalLayout_19.addWidget(self.lineEdit_MeshOutput)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtGui.QLabel(self.groupBox_OutputSettings)
        self.label_17.setMinimumSize(QtCore.QSize(100, 0))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.lineEdit_TextureOutput = QtGui.QLineEdit(self.groupBox_OutputSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_TextureOutput.sizePolicy().hasHeightForWidth())
        self.lineEdit_TextureOutput.setSizePolicy(sizePolicy)
        self.lineEdit_TextureOutput.setProperty("editable", True)
        self.lineEdit_TextureOutput.setObjectName("lineEdit_TextureOutput")
        self.horizontalLayout_16.addWidget(self.lineEdit_TextureOutput)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.verticalLayout_4.addWidget(self.groupBox_OutputSettings)
        self.groupBox_ExportingOptions = QtGui.QGroupBox(mainDialog)
        self.groupBox_ExportingOptions.setToolTip("")
        self.groupBox_ExportingOptions.setObjectName("groupBox_ExportingOptions")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_ExportingOptions)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_13 = QtGui.QLabel(self.groupBox_ExportingOptions)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_18.addWidget(self.label_13)
        self.radioButton_vForge = QtGui.QRadioButton(self.groupBox_ExportingOptions)
        self.radioButton_vForge.setChecked(True)
        self.radioButton_vForge.setObjectName("radioButton_vForge")
        self.horizontalLayout_18.addWidget(self.radioButton_vForge)
        self.radioButton_Binary = QtGui.QRadioButton(self.groupBox_ExportingOptions)
        self.radioButton_Binary.setChecked(False)
        self.radioButton_Binary.setObjectName("radioButton_Binary")
        self.horizontalLayout_18.addWidget(self.radioButton_Binary)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.checkBox_Prefab = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_Prefab.setChecked(False)
        self.checkBox_Prefab.setObjectName("checkBox_Prefab")
        self.horizontalLayout_17.addWidget(self.checkBox_Prefab)
        self.checkBox_GenerateCollisionData = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_GenerateCollisionData.setChecked(False)
        self.checkBox_GenerateCollisionData.setObjectName("checkBox_GenerateCollisionData")
        self.horizontalLayout_17.addWidget(self.checkBox_GenerateCollisionData)
        self.checkBox_MakePivotingZones = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_MakePivotingZones.setChecked(False)
        self.checkBox_MakePivotingZones.setObjectName("checkBox_MakePivotingZones")
        self.horizontalLayout_17.addWidget(self.checkBox_MakePivotingZones)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.checkBox_ConvertToDDS = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_ConvertToDDS.setChecked(True)
        self.checkBox_ConvertToDDS.setObjectName("checkBox_ConvertToDDS")
        self.horizontalLayout_20.addWidget(self.checkBox_ConvertToDDS)
        self.checkBox_FlipExistingDDS = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_FlipExistingDDS.setObjectName("checkBox_FlipExistingDDS")
        self.horizontalLayout_20.addWidget(self.checkBox_FlipExistingDDS)
        self.checkBox_HighQualityDDS = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_HighQualityDDS.setObjectName("checkBox_HighQualityDDS")
        self.horizontalLayout_20.addWidget(self.checkBox_HighQualityDDS)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.checkBox_KeepExported = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_KeepExported.setObjectName("checkBox_KeepExported")
        self.horizontalLayout_23.addWidget(self.checkBox_KeepExported)
        self.checkBox_NoMainLayer = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_NoMainLayer.setObjectName("checkBox_NoMainLayer")
        self.horizontalLayout_23.addWidget(self.checkBox_NoMainLayer)
        self.checkBox_Audit = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_Audit.setObjectName("checkBox_Audit")
        self.horizontalLayout_23.addWidget(self.checkBox_Audit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBox_FlipV = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_FlipV.setObjectName("checkBox_FlipV")
        self.horizontalLayout_13.addWidget(self.checkBox_FlipV)
        self.checkBox_CenterMeshes = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_CenterMeshes.setObjectName("checkBox_CenterMeshes")
        self.horizontalLayout_13.addWidget(self.checkBox_CenterMeshes)
        self.label_5 = QtGui.QLabel(self.groupBox_ExportingOptions)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_SkipLOD = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_SkipLOD.setMinimumSize(QtCore.QSize(130, 0))
        self.checkBox_SkipLOD.setObjectName("checkBox_SkipLOD")
        self.gridLayout.addWidget(self.checkBox_SkipLOD, 0, 0, 1, 1)
        self.lineEdit_SkipLOD = QtGui.QLineEdit(self.groupBox_ExportingOptions)
        self.lineEdit_SkipLOD.setEnabled(False)
        self.lineEdit_SkipLOD.setObjectName("lineEdit_SkipLOD")
        self.gridLayout.addWidget(self.lineEdit_SkipLOD, 0, 1, 1, 1)
        self.checkBox_TerrainLOD = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_TerrainLOD.setMinimumSize(QtCore.QSize(130, 0))
        self.checkBox_TerrainLOD.setObjectName("checkBox_TerrainLOD")
        self.gridLayout.addWidget(self.checkBox_TerrainLOD, 1, 0, 1, 1)
        self.lineEdit_TerrainLOD = QtGui.QLineEdit(self.groupBox_ExportingOptions)
        self.lineEdit_TerrainLOD.setEnabled(False)
        self.lineEdit_TerrainLOD.setObjectName("lineEdit_TerrainLOD")
        self.gridLayout.addWidget(self.lineEdit_TerrainLOD, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.checkBox_ZoneReg = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_ZoneReg.setMinimumSize(QtCore.QSize(130, 0))
        self.checkBox_ZoneReg.setObjectName("checkBox_ZoneReg")
        self.horizontalLayout_22.addWidget(self.checkBox_ZoneReg)
        self.lineEdit_ZoneReg = QtGui.QLineEdit(self.groupBox_ExportingOptions)
        self.lineEdit_ZoneReg.setEnabled(False)
        self.lineEdit_ZoneReg.setObjectName("lineEdit_ZoneReg")
        self.horizontalLayout_22.addWidget(self.lineEdit_ZoneReg)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.checkBox_AdditionalCommands = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_AdditionalCommands.setMinimumSize(QtCore.QSize(130, 0))
        self.checkBox_AdditionalCommands.setObjectName("checkBox_AdditionalCommands")
        self.horizontalLayout_27.addWidget(self.checkBox_AdditionalCommands)
        self.lineEdit_AdditionalCommands = QtGui.QLineEdit(self.groupBox_ExportingOptions)
        self.lineEdit_AdditionalCommands.setEnabled(False)
        self.lineEdit_AdditionalCommands.setText("")
        self.lineEdit_AdditionalCommands.setObjectName("lineEdit_AdditionalCommands")
        self.horizontalLayout_27.addWidget(self.lineEdit_AdditionalCommands)
        self.verticalLayout_3.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.checkBox_EnableLog = QtGui.QCheckBox(self.groupBox_ExportingOptions)
        self.checkBox_EnableLog.setMinimumSize(QtCore.QSize(130, 0))
        self.checkBox_EnableLog.setObjectName("checkBox_EnableLog")
        self.horizontalLayout_21.addWidget(self.checkBox_EnableLog)
        self.comboBox_LogFile = QtGui.QComboBox(self.groupBox_ExportingOptions)
        self.comboBox_LogFile.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_LogFile.sizePolicy().hasHeightForWidth())
        self.comboBox_LogFile.setSizePolicy(sizePolicy)
        self.comboBox_LogFile.setEditable(True)
        self.comboBox_LogFile.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.comboBox_LogFile.setObjectName("comboBox_LogFile")
        self.horizontalLayout_21.addWidget(self.comboBox_LogFile)
        self.pushButton_LogFile = QtGui.QPushButton(self.groupBox_ExportingOptions)
        self.pushButton_LogFile.setEnabled(False)
        self.pushButton_LogFile.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_LogFile.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_LogFile.setText("")
        self.pushButton_LogFile.setIcon(icon4)
        self.pushButton_LogFile.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_LogFile.setObjectName("pushButton_LogFile")
        self.horizontalLayout_21.addWidget(self.pushButton_LogFile)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.verticalLayout_4.addWidget(self.groupBox_ExportingOptions)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.resetButton = QtGui.QPushButton(mainDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setMinimumSize(QtCore.QSize(100, 40))
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_24.addWidget(self.resetButton)
        self.showButton = QtGui.QPushButton(mainDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showButton.sizePolicy().hasHeightForWidth())
        self.showButton.setSizePolicy(sizePolicy)
        self.showButton.setMinimumSize(QtCore.QSize(100, 40))
        self.showButton.setToolTip("")
        self.showButton.setObjectName("showButton")
        self.horizontalLayout_24.addWidget(self.showButton)
        spacerItem = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem)
        self.saveButton = QtGui.QPushButton(mainDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMinimumSize(QtCore.QSize(100, 40))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_24.addWidget(self.saveButton)
        self.convertButton = QtGui.QPushButton(mainDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convertButton.sizePolicy().hasHeightForWidth())
        self.convertButton.setSizePolicy(sizePolicy)
        self.convertButton.setMinimumSize(QtCore.QSize(100, 40))
        self.convertButton.setObjectName("convertButton")
        self.horizontalLayout_24.addWidget(self.convertButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)

        self.retranslateUi(mainDialog)
        QtCore.QObject.connect(self.checkBox_SkipLOD, QtCore.SIGNAL("toggled(bool)"), self.lineEdit_SkipLOD.setEnabled)
        QtCore.QObject.connect(self.checkBox_EnableLog, QtCore.SIGNAL("toggled(bool)"), self.comboBox_LogFile.setEnabled)
        QtCore.QObject.connect(self.checkBox_EnableLog, QtCore.SIGNAL("toggled(bool)"), self.pushButton_LogFile.setEnabled)
        QtCore.QObject.connect(self.checkBox_ZoneReg, QtCore.SIGNAL("toggled(bool)"), self.lineEdit_ZoneReg.setEnabled)
        QtCore.QObject.connect(self.checkBox_TerrainLOD, QtCore.SIGNAL("toggled(bool)"), self.lineEdit_TerrainLOD.setEnabled)
        QtCore.QObject.connect(self.checkBox_ConvertToDDS, QtCore.SIGNAL("toggled(bool)"), self.checkBox_FlipExistingDDS.setEnabled)
        QtCore.QObject.connect(self.checkBox_ConvertToDDS, QtCore.SIGNAL("toggled(bool)"), self.checkBox_HighQualityDDS.setEnabled)
        QtCore.QObject.connect(self.checkBox_AdditionalCommands, QtCore.SIGNAL("toggled(bool)"), self.lineEdit_AdditionalCommands.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(mainDialog)

    def retranslateUi(self, mainDialog):
        mainDialog.setWindowTitle(QtGui.QApplication.translate("mainDialog", "Havok OpenFlight Converter", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainDialog", "       OpenFlight Converter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setToolTip(QtGui.QApplication.translate("mainDialog", "Choose a profile.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("mainDialog", "Current Profile :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Profile.setToolTip(QtGui.QApplication.translate("mainDialog", "Choose a profile.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_renameProfile.setToolTip(QtGui.QApplication.translate("mainDialog", "Edit the name of the selected profile.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AddProfile.setToolTip(QtGui.QApplication.translate("mainDialog", "Add a new profile.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DelProfile.setToolTip(QtGui.QApplication.translate("mainDialog", "Delete the selected profile.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_InputSettings.setTitle(QtGui.QApplication.translate("mainDialog", "Input Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("mainDialog", "Choose a converter.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainDialog", "Converter :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Converter.setToolTip(QtGui.QApplication.translate("mainDialog", "The converters you picked last time are displayed here.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setToolTip(QtGui.QApplication.translate("mainDialog", "Input file.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mainDialog", "Input File :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_InputFile.setToolTip(QtGui.QApplication.translate("mainDialog", "Input file.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("mainDialog", "This is the folder where the .flt files are stored.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mainDialog", "OpenFlight Path :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_OpenFlightPath.setToolTip(QtGui.QApplication.translate("mainDialog", "This is the folder where the .flt files are stored.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setToolTip(QtGui.QApplication.translate("mainDialog", "This is the folder where the texures are stored.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("mainDialog", "Texture Path :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_TextureInput.setToolTip(QtGui.QApplication.translate("mainDialog", "This is the folder where the texures are stored.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setToolTip(QtGui.QApplication.translate("mainDialog", "System configuration file.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("mainDialog", "Config File :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ConfigFile.setToolTip(QtGui.QApplication.translate("mainDialog", "System configuration file.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_OutputSettings.setTitle(QtGui.QApplication.translate("mainDialog", "Output Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setToolTip(QtGui.QApplication.translate("mainDialog", "Workspace directory, where project will be exported.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("mainDialog", "Export Path :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_WorkPath.setToolTip(QtGui.QApplication.translate("mainDialog", "Workspace directory, where the project will be exported.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setToolTip(QtGui.QApplication.translate("mainDialog", "Give the scene a name.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("mainDialog", "    Scene Name :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_LayerOutput.setToolTip(QtGui.QApplication.translate("mainDialog", "Give the scene a name.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setToolTip(QtGui.QApplication.translate("mainDialog", "Physics output directory.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("mainDialog", "    Physics Folder :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_PhysicsOutput.setToolTip(QtGui.QApplication.translate("mainDialog", "Physics output path, don\'t use slash at the end. It will be appended by exporter.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setToolTip(QtGui.QApplication.translate("mainDialog", "Mesh output directory.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("mainDialog", "    Mesh Folder :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_MeshOutput.setToolTip(QtGui.QApplication.translate("mainDialog", "Mesh output path.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setToolTip(QtGui.QApplication.translate("mainDialog", "Texture output directory.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("mainDialog", "        Texture Folder :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_TextureOutput.setToolTip(QtGui.QApplication.translate("mainDialog", "Texture is referenced as meshOutputPath + texturePath + textureName.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_ExportingOptions.setTitle(QtGui.QApplication.translate("mainDialog", "Exporting Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("mainDialog", "Exporting Type: ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_vForge.setText(QtGui.QApplication.translate("mainDialog", "vForge", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_Binary.setText(QtGui.QApplication.translate("mainDialog", "Binary", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Prefab.setToolTip(QtGui.QApplication.translate("mainDialog", "Export as a prefab.  This defaults to exporting models.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Prefab.setText(QtGui.QApplication.translate("mainDialog", "Prefab", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_GenerateCollisionData.setText(QtGui.QApplication.translate("mainDialog", "Generate Collision Data", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_MakePivotingZones.setToolTip(QtGui.QApplication.translate("mainDialog", "Enable pivots in exported zones (often used w/ -centermeshes).", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_MakePivotingZones.setText(QtGui.QApplication.translate("mainDialog", "Make Pivoting Zones", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ConvertToDDS.setToolTip(QtGui.QApplication.translate("mainDialog", "Convert input textures to dds textures at textureOutputPath.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ConvertToDDS.setText(QtGui.QApplication.translate("mainDialog", "Convert To DDS", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_FlipExistingDDS.setToolTip(QtGui.QApplication.translate("mainDialog", "Flip existing dds textures at textureOutputPath.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_FlipExistingDDS.setText(QtGui.QApplication.translate("mainDialog", "Flip Existing DDS", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_HighQualityDDS.setToolTip(QtGui.QApplication.translate("mainDialog", "High quality DDS compression (export may take much longer, use it for production quality).", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_HighQualityDDS.setText(QtGui.QApplication.translate("mainDialog", "High Quality DDS", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_KeepExported.setToolTip(QtGui.QApplication.translate("mainDialog", "Do not delete previously exported zone/layer files.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_KeepExported.setText(QtGui.QApplication.translate("mainDialog", "Keep Exported", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_NoMainLayer.setToolTip(QtGui.QApplication.translate("mainDialog", "Do not generate any default scene settings for xml export.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_NoMainLayer.setText(QtGui.QApplication.translate("mainDialog", "No Main Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Audit.setToolTip(QtGui.QApplication.translate("mainDialog", "Show information about files which match the patterns from the configuration file.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_Audit.setText(QtGui.QApplication.translate("mainDialog", "Audit", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_FlipV.setToolTip(QtGui.QApplication.translate("mainDialog", "Flip v coordinate of textures.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_FlipV.setText(QtGui.QApplication.translate("mainDialog", "Flip V", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_CenterMeshes.setToolTip(QtGui.QApplication.translate("mainDialog", "Default behavior for a mesh is to recenter it.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_CenterMeshes.setText(QtGui.QApplication.translate("mainDialog", "Center Meshes", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_SkipLOD.setToolTip(QtGui.QApplication.translate("mainDialog", "A semicolon separated filter containing wildcards specifying which files to skip fpr LOD. e.g. *debris*;*tree* \"", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_SkipLOD.setText(QtGui.QApplication.translate("mainDialog", "Skip LOD Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_SkipLOD.setToolTip(QtGui.QApplication.translate("mainDialog", "A semicolon separated filter containing wildcards specifying which files to skip fpr LOD. e.g. *debris*;*tree* \"", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_SkipLOD.setPlaceholderText(QtGui.QApplication.translate("mainDialog", "*debris*;*tree*", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_TerrainLOD.setToolTip(QtGui.QApplication.translate("mainDialog", "A semicolon separated filter containing wildcards specifying which files to generate terrain LODs. e.g. *fligth*;*terrain*", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_TerrainLOD.setText(QtGui.QApplication.translate("mainDialog", "Terrain LOD Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_TerrainLOD.setToolTip(QtGui.QApplication.translate("mainDialog", "A semicolon separated filter containing wildcards specifying which files to generate terrain LODs. e.g. *fligth*;*terrain*", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_TerrainLOD.setPlaceholderText(QtGui.QApplication.translate("mainDialog", "*flight*;*terrain*", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ZoneReg.setToolTip(QtGui.QApplication.translate("mainDialog", "Regex matching for a default zone setup in creating a scene.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ZoneReg.setText(QtGui.QApplication.translate("mainDialog", "Defualt Zone Regex", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ZoneReg.setToolTip(QtGui.QApplication.translate("mainDialog", "Regex matching for a default zone setup in creating a scene.", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ZoneReg.setText(QtGui.QApplication.translate("mainDialog", ".*?", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_AdditionalCommands.setToolTip(QtGui.QApplication.translate("mainDialog", "Regex matching for a default zone setup in creating a scene.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_AdditionalCommands.setText(QtGui.QApplication.translate("mainDialog", "Additional Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_AdditionalCommands.setToolTip(QtGui.QApplication.translate("mainDialog", "Additional commands should be seperated by ;", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_AdditionalCommands.setPlaceholderText(QtGui.QApplication.translate("mainDialog", "-Command_A [value];-Command_B", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_EnableLog.setToolTip(QtGui.QApplication.translate("mainDialog", "Enable logging; default settings go to printf & log everything.  This can be customized in the configuration file.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_EnableLog.setText(QtGui.QApplication.translate("mainDialog", "Enable Log", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_LogFile.setToolTip(QtGui.QApplication.translate("mainDialog", "Log to a particular file; this can be overriden by settings in the configuration file.", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setToolTip(QtGui.QApplication.translate("mainDialog", "Reset all fields.", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("mainDialog", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.showButton.setText(QtGui.QApplication.translate("mainDialog", "Show Less", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setToolTip(QtGui.QApplication.translate("mainDialog", "Save as a bacth file.", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("mainDialog", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.convertButton.setToolTip(QtGui.QApplication.translate("mainDialog", "Convert it now.", None, QtGui.QApplication.UnicodeUTF8))
        self.convertButton.setText(QtGui.QApplication.translate("mainDialog", "Convert", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
